### ISSUE TITLE
Try new validations in mkdocs `1.6.0` (after upgrading `mkdocs-material`)

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovatebot.github.io#439]
### What would you like to be able to do?

`mkdocs 1.6.0`  can warn us about broken absolute links and broken anchors in links (`#anchor`). I would definitely like to try these new warnings on our docs, to help catch broken stuff before creating a new build of the docs.

But `mkdocs-material` does not support `mkdocs 1.6.0` yet. So we need to wait for a version of `mkdocs-material` that support the new `mkdocs`.

### Did you already have any implementation ideas?

Here's a list of todos:

- [x] Upgrade to a version of `mkdocs-material` that supports `mkdocs 1.6.0`
- [x] Read the [`mkdocs` 1.6.0 changelog](https://www.mkdocs.org/about/release-notes/#version-160-2024-04-20) to check for important changes
- [x] Update to `mkdocs 1.6.0`
- [x] Try the new options for validation of hyperlinks between pages:
  - [x] [validate absolute links](https://www.mkdocs.org/about/release-notes/#absolute-links-within-nav) I think we should keep this set to `absolute_links: warn` so we're "forced" to use relative links.
  - [x] [validate anchors in links](https://www.mkdocs.org/about/release-notes/#anchors)
  - [x] Read the [MkDocs validation section](https://www.mkdocs.org/user-guide/configuration/#validation) and try the recommended settings for most sites (maximal strictness):
    ```yaml
    validation:
      omitted_files: warn
      absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
      unrecognized_links: warn
      anchors: warn  # New in MkDocs 1.6
    ```

I'm willing to try configuring the new settings for us, and helping to update. :smile: 

### Do you want to write this feature yourself?

Yes
